routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Client\ProductController;
use App\Http\Controllers\Client\MaterialController;
use App\Http\Controllers\Client\WarehouseController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products',ProductController::class);
Route::resource('materials',MaterialController::class);
Route::resource('warehouses',WarehouseController::class);

resources/views/warehouses/create.blade.php
@extends('layouts.main1')
@section('content')
            <form method="post" action="{{route('warehouses.store')}}">
                @csrf
                <div class="form-group">
                    <label for="material_id">Mahsulotni tanlang:</label>
                    <select name="material_id" class="form-control">
                        <option value=""></option>
                        @foreach($materials as $material)
                            <option value="{{$material->id}}">{{$material->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="title">Partiyadagi Xomashyo qoldig`i:</label>
                    <input type="text" class="form-control" name="remainder"/>
                </div>
                <div class="form-group">
                    <label for="title">Partiyadagi xomashyo narxi:</label>
                    <input type="text" class="form-control" name="price"/>
                </div>
                <button type="submit" class="btn btn-primary">Saqlash</button>
            </form>
@endsection

resources/views/warehouses/index.blade.php
@extends('layouts.main1')
@section('content')
    <h2 align="center">Omborlar</h2><a href="{{route('warehouses.create')}}">Yangi qo'shish</a>
    <table class="table table-sm my-2">
        <thead class="thead-dark">
        <tr>
            <td>№</td>
            <td>Material</td>
            <td>Soni</td>
            <td>Narxi</td>
            <td>O'chrish</td>
        </tr>
        </thead>
        <tbody>
@foreach($warehouses as $key => $warehouse)
    <tr>
        <td>{{++$key}}</td>
        <td>{{$warehouse->material_id}}</td>
        <td>{{$warehouse->remainder}}</td>
        <td>{{$warehouse->price}}</td>
        <td>
            <form action="{{route('warehouses.destroy', $warehouse->id)}}" method="post">
                @csrf
                @method('DELETE')
                <div class="btn-group btn-group-sm" role="group"><button class="btn btn-danger" type="submit" onclick="return confirm('{{$warehouse->id}}')">O'chirish</button></div>
            </form>
            </td>
    </tr>
@endforeach
        </tbody>
    </table>
@endsection