routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Client\ProductController;
use App\Http\Controllers\Client\MaterialController;
use App\Http\Controllers\Client\WarehouseController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products',ProductController::class);
Route::resource('materials',MaterialController::class);
Route::resource('warehouses',WarehouseController::class);

app/Models/v1/Material.php
<?php

namespace App\Models\v1;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Material extends Model
{
    use HasFactory;
}

app/Http/Controllers/Api/v1/MaterialController.php
<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Api\v1\BaseControllerForApi;
use Illuminate\Http\Request;
use App\Models\v1\Material;

class MaterialController extends BaseControllerForApi
{
    public function index(){
        $materials = Material::all();
        return $this->responseSuccess($materials);
    }

    public function store(Request $request){
        $material = new Material();
        $material->name = $request->name;
        $material->save();
        if ($material == true){
            return $this->responseSave($material);
        }
    }

    public function destroy($id){
        $material = Material::destroy($id);
        if ($material == true){
            return $this->responseDelete($material);
        }
    }
}

app/Http/Controllers/Client/MaterialController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Client\BaseControllerForClient;
use Illuminate\Http\Request;

class MaterialController extends BaseControllerForClient
{
    public function index(){
        $materials = $this->get('http://mahsulot.loc/api/materials');
        return view('materials.index',[
            'materials' => $materials->data
        ]);
    }

    public function create(){
        return view('materials.create');
    }

    public function store(Request $request){
        $request = $this->post('http://mahsulot.loc/api/materials',$request->except('_token'));
        if ($request == true){
            return redirect()->route('materials.index');
        }
    }

    public function destroy($id){
        $material = $this->delete('http://mahsulot.loc/api/materials/'.$id);
        if ($material == true){
            return redirect()->route('materials.index');
        }
    }
}

resources/views/materials/create.blade.php
@extends('layouts.main1')
@section('content')
            <form method="post" action="{{route('materials.store')}}">
                @csrf
                <div class="form-group">
                    <label for="title">Xomashyo nomi:</label>
                    <input type="text" class="form-control" name="name"/>
                </div>
                <button type="submit" class="btn btn-primary">Saqlash</button>
            </form>
@endsection

resources/views/materials/index.blade.php
@extends('layouts.main1')
@section('content')
    <h2 align="center">Xomashyolar</h2><a href="{{route('materials.create')}}">Yangi qo'shish</a>
    <table class="table table-sm my-2">
        <thead class="thead-dark">
        <tr>
            <td>№</td>
            <td>Nomi</td>
            <td>O'chrish</td>
        </tr>
        </thead>
        <tbody>
@foreach($materials as $key => $material)
    <tr>
        <td>{{++$key}}</td>
        <td>{{$material->name}}</td>
        <td>
            <form action="{{route('materials.destroy', $material->id)}}" method="post">
                @csrf
                @method('DELETE')
                <div class="btn-group btn-group-sm" role="group"><button class="btn btn-danger" type="submit" onclick="return confirm('{{$material->name}}')">O'chirish</button></div>
            </form>
            </td>
    </tr>
@endforeach
        </tbody>
    </table>
@endsection