routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Client\ProductController;
use App\Http\Controllers\Client\MaterialController;
use App\Http\Controllers\Client\WarehouseController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products',ProductController::class);
Route::resource('materials',MaterialController::class);
Route::resource('warehouses',WarehouseController::class);

app/Models/v1/Product.php
<?php

namespace App\Models\v1;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;


class Product extends Model
{
    use HasFactory;

    public static function getByProduct($product_id,$amount){
        $warehouse = DB::table('warehouses')
            ->leftJoin('product_materials','product_materials.material_id','=','warehouses.material_id')
            ->leftJoin('materials','warehouses.material_id','=','materials.id')
           /* ->join('products','products.id','=','product_materials.product_id')*/
            ->select(/*'products.name as product_name',*/'warehouses.id as warehouse_id','warehouses.remainder as qty','warehouses.price as price','materials.name as material_name')
            ->where(['product_materials.product_id' => $product_id])
            ->get();
        $productMaterial = DB::table('product_materials')
            ->leftJoin('products','product_materials.product_id','=','products.id')
            ->leftJoin('materials','product_materials.material_id','=','materials.id')
            ->select('materials.name as material_name','product_materials.quantity as qty')
            ->where('products.id','=',$product_id)
            ->get();
        $product = DB::table('products')
            ->select('products.name as product_name')
            ->where('products.id','=',$product_id)
            ->get();
        //Count

        $productMaterialCount = DB::table('product_materials')->select('quantity')
            ->where(['material_id'=>1,'product_id'=>$product_id])
            ->sum('quantity');
        $productMaterialCount2 = DB::table('product_materials')->select('quantity')
            ->where(['material_id'=>2,'product_id'=>$product_id])
            ->sum('quantity');
        $productMaterialCount3 = DB::table('product_materials')->select('quantity')
            ->where(['material_id'=>3,'product_id'=>$product_id])
            ->sum('quantity');
        $productMaterialCount4 = DB::table('product_materials')->select('quantity')
            ->where(['material_id'=>4,'product_id'=>$product_id])
            ->sum('quantity');
        return ['result' =>$product,'product_materials' => $warehouse,'Mato' => $productMaterialCount*$amount, 'Ip' => $productMaterialCount2*$amount,
            'Tugma' => $productMaterialCount3*$amount, 'Zamok' => $productMaterialCount4*$amount];
    }
}

app/Http/Controllers/Api/v1/ProductController.php
<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Api\v1\BaseControllerForApi;
use Illuminate\Http\Request;
use App\Models\v1\Product;

class ProductController extends BaseControllerForApi
{
    public function index(){
        $products = Product::all();
        return $this->responseSuccess($products);
    }

    public function store(Request $request){
        $product = new Product();
        $product->name = $request->name;
        $product->code = $request->code;
        $product->save();
        if ($product == true){
            return $this->responseSuccess($product);
        }
    }

    public function destroy($id){
        $product = Product::destroy($id);
        return $this->responseDelete($product);
    }
}

app/Http/Controllers/Client/ProductController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Client\BaseControllerForClient;
use Illuminate\Http\Request;

class ProductController extends BaseControllerForClient
{
    public function index(){
        $products = $this->get('http://mahsulot.loc/api/products');
        return view('products.index',[
            'products' => $products->data
            ]);
    }

    public function create(){
        return view('products.create');
    }

    public function store(Request $request){
        $request = $this->post('http://mahsulot.loc/api/products',$request->except('_token'));
        if ($request == true){
            return redirect()->route('products.index');
        }
    }

    public function destroy($id){
        $product = $this->delete('http://mahsulot.loc/api/products/'.$id);
        if ($product == true){
            return redirect()->route('products.index');
        }
    }
}

resources/views/products/create.blade.php
@extends('layouts.main1')
@section('content')
            <form method="post" action="{{route('products.store')}}">
                @csrf
                <div class="form-group">
                    <label for="title">Mahsulot nomi:</label>
                    <input type="text" class="form-control" name="name"/>
                </div>
                <div class="form-group">
                    <label for="title">Mahsulot kodi:</label>
                    <input type="text" class="form-control" name="code"/>
                </div>
                <button type="submit" class="btn btn-primary">Saqlash</button>
            </form>
@endsection

resources/views/products/index.blade.php
@extends('layouts.main1')
@section('content')
    <h2 align="center">Mahsulotlar</h2><a href="{{route('products.create')}}">Yangi qo'shish</a>
    <table class="table table-sm my-2">
        <thead class="thead-dark">
        <tr>
            <td>№</td>
            <td>Nomi</td>
            <td>Kodi</td>
            <td>O'chrish</td>
        </tr>
        </thead>
        <tbody>
@foreach($products as $key => $product)
    <tr>
        <td>{{++$key}}</td>
        <td>{{$product->name}}</td>
        <td>{{$product->code}}</td>
        <td>
            <form action="{{route('products.destroy', $product->id)}}" method="post">
                @csrf
                @method('DELETE')
                <div class="btn-group btn-group-sm" role="group"><button class="btn btn-danger" type="submit" onclick="return confirm('{{$product->name}}')">O'chirish</button></div>
            </form>
            </td>
    </tr>
@endforeach
        </tbody>
    </table>
@endsection